// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCePJ6DgHlMBa4UDVGaRg-SOO_x7YrmVEo',
    appId: '1:826458711126:web:10f306d5c425f48cc047f7',
    messagingSenderId: '826458711126',
    projectId: 'gdsc-6704d',
    authDomain: 'gdsc-6704d.firebaseapp.com',
    storageBucket: 'gdsc-6704d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6xeUF1BJBbY4QfX_Ut1NModfrhRm4xUg',
    appId: '1:826458711126:android:a3c5d8b0b41dcc19c047f7',
    messagingSenderId: '826458711126',
    projectId: 'gdsc-6704d',
    storageBucket: 'gdsc-6704d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtQldGSR3yHtamED-HBxhyGBnOYDoE7RI',
    appId: '1:826458711126:ios:467e86c2994d5c06c047f7',
    messagingSenderId: '826458711126',
    projectId: 'gdsc-6704d',
    storageBucket: 'gdsc-6704d.appspot.com',
    iosClientId: '826458711126-8ercqa134q7gn584kjdio2389onos4qr.apps.googleusercontent.com',
    iosBundleId: 'com.example.gdscApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBtQldGSR3yHtamED-HBxhyGBnOYDoE7RI',
    appId: '1:826458711126:ios:0ce515c70c0b89f9c047f7',
    messagingSenderId: '826458711126',
    projectId: 'gdsc-6704d',
    storageBucket: 'gdsc-6704d.appspot.com',
    iosClientId: '826458711126-p8lem4qa3lbhahufenhqqpv554m518f8.apps.googleusercontent.com',
    iosBundleId: 'com.example.gdscApp.RunnerTests',
  );
}
